# fly.toml app configuration file generated for datingapp-weathered-breeze-9206 on 2024-08-18T14:53:43+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingapp-weathered-breeze-9206'
primary_region = 'otp'

[build]
  image = 'thewickermilko/datingapp:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dqokwsoeu"
  CloudinarySettings__ApiKey="232178442655588"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
